services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: janusdb
      POSTGRES_USER: black
      POSTGRES_PASSWORD: black
      TZ: Asia/Seoul
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"