spring:
  application:
    name: recipe

  datasource:
    url: jdbc:postgresql://localhost:5432/janusdb
    username: black
    password: black
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 50
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

springdoc:
  api-docs:
    path: /api/v1/janus/api-docs
  swagger-ui:
    path: /api/v1/janus/swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
