name: Build & Send Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker Image
        run: docker build -t janus:0.1 .

      - name: Save Docker image to tar
        run: docker save janus:0.1 -o janus.tar

      - name: Fix permission (local)
        run: sudo chmod 777 janus.tar

      # --------------------
      #   SCP: tar 파일 업로드
      # --------------------
      - name: Send image via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "janus.tar"
          target: "/home/${{ secrets.SSH_USER }}/janusSpec/"
          tar_dereference: false
          rm: false
          strip_components: 0

      # --------------------
      #   SSH: 서버에서 재배포 자동 실행
      # --------------------
      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/janusSpec

            echo "[1] Load docker image"
            docker load -i janus.tar

            echo "[2] Stop previous container"
            cd bakend
            docker compose down || true

            echo "[3] Start new container"
            docker compose up -d

            echo "[4] Done!"
